### ISSUE TITLE
Bulk e-mails versturen zorgt voor vollopende queues en vertragingen in het systeem

### ISSUE THREAD

**Issue by nielswitte** [nielswitte/assistance-online-status-page#2]
Een grote hoeveelheid e-mails tegelijkertijd versturen, zoals bijvoorbeeld bij het bevestigen van meerdere facturen, zorgt voor vertraging in het systeem. Waardoor andere processen fout gaan en uiteindelijk e-mails meerdere malen verstuurd worden.

**Comment by rikbosch** [comment]
commentaar
